/**
 * Book of Shades - AI "Rate My Book" Engine Contracts & Service Layer
 * Multi-dimensional literary craft feedback system.
 */

export interface AICritiqueInput {
  title: string;
  synopsis?: string;
  genre?: string;
  targetAudience?: string;
  authorGoals?: string;
  content: string; // chapter text or manuscript excerpt
}

export interface AICritiqueScores {
  overallScore: number; // 0 - 100
  pacing: number; // 0 - 100
  characterization: number; // 0 - 100
  dialogue: number; // 0 - 100
  worldBuilding: number; // 0 - 100
  structure: number; // 0 - 100
  readability: number; // 0 - 100
}

export interface AICritiqueFeedback {
  scores: AICritiqueScores;
  strengths: string[];
  weaknesses: string[];
  actionableSuggestions: string[];
  comparableThemes: string[];
  potentialAudience: string;
  disclaimer: string;
}

export const AI_CRITIQUE_SYSTEM_PROMPT = `You are an expert literary editor, narrative analyst, and creative writing consultant for the publishing platform "Book of Shades".
Your mission is to provide constructive, honest, and actionable structural feedback on the author's submitted work.
Do not assign a single arbitrary vanity score without grounding it in craft.
Analyze the following dimensions:
1. Plot & Narrative Structure
2. Characterization & Voice
3. Pacing & Tension Progression
4. Dialogue Naturalism & Subtext
5. World-Building & Exposition Balance
6. Grammar, Style & Readability

Always return your response as a valid JSON object matching this schema:
{
  "scores": {
    "overallScore": number (0-100),
    "pacing": number (0-100),
    "characterization": number (0-100),
    "dialogue": number (0-100),
    "worldBuilding": number (0-100),
    "structure": number (0-100),
    "readability": number (0-100)
  },
  "strengths": [string, string, ...],
  "weaknesses": [string, string, ...],
  "actionableSuggestions": [string, string, ...],
  "comparableThemes": [string, ...],
  "potentialAudience": string,
  "disclaimer": "This analysis is advisory and generated by AI to assist in revision, not a literary verdict."
}`;
