"use client";

import { useState } from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import {
  PenTool,
  Sparkles,
  BookOpen,
  Image as ImageIcon,
  DollarSign,
  Send,
  Save,
  CheckCircle2,
  AlertCircle,
  Clock,
  Layers,
  ShieldAlert,
  BarChart2,
  Upload,
} from "lucide-react";
import { AICritiqueFeedback } from "@/lib/ai-critique";

export default function CreateStudioPage() {
  const [activeTab, setActiveTab] = useState<"details" | "editor" | "release" | "ai">("details");

  // Form states
  const [title, setTitle] = useState("");
  const [workType, setWorkType] = useState<string>("NOVEL");
  const [description, setDescription] = useState("");
  const [ageRating, setAgeRating] = useState("TEEN");
  const [genre, setGenre] = useState("Fantasy");

  // Chapter editor states
  const [chapterTitle, setChapterTitle] = useState("");
  const [chapterBody, setChapterBody] = useState("");

  // Monetization model
  const [monetizationModel, setMonetizationModel] = useState<"FREE" | "MEMBERS_FIRST" | "PAID">("MEMBERS_FIRST");
  const [membersFirstDays, setMembersFirstDays] = useState(7);
  const [price, setPrice] = useState("1.99");

  // AI Critique State
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [aiFeedback, setAiFeedback] = useState<AICritiqueFeedback | null>(null);

  const wordCount = chapterBody.trim() ? chapterBody.trim().split(/\s+/).length : 0;

  const handleRunAICritique = () => {
    if (!chapterBody.trim()) {
      alert("Please write or paste some chapter text in the Chapter Content tab first!");
      return;
    }

    setIsAnalyzing(true);
    setActiveTab("ai");

    setTimeout(() => {
      setAiFeedback({
        scores: {
          overallScore: 88,
          pacing: 92,
          characterization: 85,
          dialogue: 89,
          worldBuilding: 94,
          structure: 86,
          readability: 91,
        },
        strengths: [
          "Evocative atmospheric sensory details in the opening setting description.",
          "Natural dialogue cadence with good subtext and tension between characters.",
          "High narrative hook that compels the reader to read the next scene.",
        ],
        weaknesses: [
          "Slight exposition density in paragraph 4 regarding ancient history.",
          "Protagonist's internal emotional stakes could be introduced earlier.",
        ],
        actionableSuggestions: [
          "Break up the ley-line explanation by showing a practical spell failure rather than explaining the law.",
          "Add a fleeting sensory detail about the scent of ozone or rain to heighten the magic manifestation scene.",
        ],
        comparableThemes: ["The Name of the Wind", "Shadow and Bone", "Fullmetal Alchemist"],
        potentialAudience: "Young Adult & New Adult Dark Fantasy readers who enjoy intricate magic systems.",
        disclaimer: "This analysis is advisory and generated by AI to assist in revision, not a literary verdict.",
      });
      setIsAnalyzing(false);
    }, 1500);
  };

  return (
    <div className="min-h-screen bg-[#09090b] text-zinc-100 flex flex-col selection:bg-violet-600">
      <Navbar />

      <main className="flex-1 max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
        {/* Studio Top Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-6 border-b border-zinc-800">
          <div>
            <div className="flex items-center gap-2">
              <span className="p-1.5 rounded-lg bg-violet-600/20 text-violet-400 border border-violet-500/30">
                <PenTool className="w-5 h-5" />
              </span>
              <h1 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
                Creator Publishing Studio
              </h1>
            </div>
            <p className="text-xs sm:text-sm text-zinc-400 mt-1">
              Create, draft, critique with AI, and publish your serialized text or manga works.
            </p>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={() => alert("Draft saved locally!")}
              className="px-4 py-2 rounded-xl bg-zinc-900 hover:bg-zinc-800 border border-zinc-800 text-xs font-semibold text-zinc-300 flex items-center gap-1.5 transition-colors"
            >
              <Save className="w-3.5 h-3.5" /> Save Draft
            </button>

            <button
              onClick={() => alert("Congratulations! Your work has been published to the platform.")}
              className="px-5 py-2 rounded-xl bg-gradient-to-r from-violet-600 to-fuchsia-600 hover:from-violet-500 hover:to-fuchsia-500 text-white text-xs font-bold shadow-md shadow-violet-600/30 flex items-center gap-1.5 transition-all"
            >
              <Send className="w-3.5 h-3.5" /> Publish Release
            </button>
          </div>
        </div>

        {/* Studio Tabs Navigation */}
        <div className="flex flex-wrap items-center gap-2 p-1.5 rounded-2xl bg-zinc-900/90 border border-zinc-800">
          <button
            onClick={() => setActiveTab("details")}
            className={`px-4 py-2 rounded-xl text-xs font-semibold flex items-center gap-2 transition-all ${
              activeTab === "details"
                ? "bg-violet-600 text-white shadow-sm"
                : "text-zinc-400 hover:text-zinc-200"
            }`}
          >
            <BookOpen className="w-4 h-4" /> 1. Work Details
          </button>

          <button
            onClick={() => setActiveTab("editor")}
            className={`px-4 py-2 rounded-xl text-xs font-semibold flex items-center gap-2 transition-all ${
              activeTab === "editor"
                ? "bg-violet-600 text-white shadow-sm"
                : "text-zinc-400 hover:text-zinc-200"
            }`}
          >
            <PenTool className="w-4 h-4" /> 2. Chapter Content ({wordCount} words)
          </button>

          <button
            onClick={() => setActiveTab("release")}
            className={`px-4 py-2 rounded-xl text-xs font-semibold flex items-center gap-2 transition-all ${
              activeTab === "release"
                ? "bg-violet-600 text-white shadow-sm"
                : "text-zinc-400 hover:text-zinc-200"
            }`}
          >
            <DollarSign className="w-4 h-4" /> 3. Release & Monetization
          </button>

          <button
            onClick={() => setActiveTab("ai")}
            className={`px-4 py-2 rounded-xl text-xs font-semibold flex items-center gap-2 transition-all ${
              activeTab === "ai"
                ? "bg-gradient-to-r from-amber-500 to-fuchsia-600 text-white shadow-sm"
                : "text-amber-400 hover:text-amber-300"
            }`}
          >
            <Sparkles className="w-4 h-4" /> 4. AI Rate My Book
          </button>
        </div>

        {/* Tab 1: Work Details Form */}
        {activeTab === "details" && (
          <div className="glass-panel p-6 sm:p-8 rounded-3xl border border-zinc-800 space-y-6 animate-in fade-in duration-200">
            <h3 className="text-lg font-bold text-white">Work Metadata & Categorization</h3>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-2">
                <label className="text-xs font-bold text-zinc-300">Story or Series Title</label>
                <input
                  type="text"
                  placeholder="e.g., The Chronomancer of Aethelgard"
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  className="w-full px-4 py-2.5 bg-zinc-900 border border-zinc-800 rounded-xl text-sm text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-violet-500"
                />
              </div>

              <div className="space-y-2">
                <label className="text-xs font-bold text-zinc-300">Content Medium / Format</label>
                <select
                  value={workType}
                  onChange={(e) => setWorkType(e.target.value)}
                  className="w-full px-4 py-2.5 bg-zinc-900 border border-zinc-800 rounded-xl text-sm text-zinc-100 focus:outline-none focus:border-violet-500"
                >
                  <option value="NOVEL">Novel / Serial (Text Chapters)</option>
                  <option value="MANGA">Manga / Webtoon (Image Pages)</option>
                  <option value="LIGHT_NOVEL">Light Novel (Text + Illustrations)</option>
                  <option value="SHORT_STORY">Short Story (Standalone)</option>
                  <option value="POETRY">Poetry & Verse</option>
                  <option value="NON_FICTION">Non-Fiction & Essays</option>
                </select>
              </div>

              <div className="space-y-2">
                <label className="text-xs font-bold text-zinc-300">Primary Genre</label>
                <select
                  value={genre}
                  onChange={(e) => setGenre(e.target.value)}
                  className="w-full px-4 py-2.5 bg-zinc-900 border border-zinc-800 rounded-xl text-sm text-zinc-100 focus:outline-none focus:border-violet-500"
                >
                  <option value="Fantasy">Fantasy</option>
                  <option value="Sci-Fi">Sci-Fi & Cyberpunk</option>
                  <option value="Manga & Comics">Manga & Comics</option>
                  <option value="Action & Adventure">Action & Adventure</option>
                  <option value="Romance">Romance</option>
                  <option value="Horror & Supernatural">Horror & Supernatural</option>
                  <option value="Mystery">Mystery & Detective</option>
                </select>
              </div>

              <div className="space-y-2">
                <label className="text-xs font-bold text-zinc-300">Age Rating & Content Advisory</label>
                <select
                  value={ageRating}
                  onChange={(e) => setAgeRating(e.target.value)}
                  className="w-full px-4 py-2.5 bg-zinc-900 border border-zinc-800 rounded-xl text-sm text-zinc-100 focus:outline-none focus:border-violet-500"
                >
                  <option value="EVERYONE">Everyone (General Audience)</option>
                  <option value="TEEN">Teen (13+)</option>
                  <option value="MATURE">Mature (17+)</option>
                  <option value="EXPLICIT">Explicit / Restricted</option>
                </select>
              </div>

              <div className="md:col-span-2 space-y-2">
                <label className="text-xs font-bold text-zinc-300">Synopsis & Logline</label>
                <textarea
                  rows={4}
                  placeholder="Hook your readers with a compelling summary of your world, conflict, and protagonist..."
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  className="w-full px-4 py-3 bg-zinc-900 border border-zinc-800 rounded-xl text-sm text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-violet-500 leading-relaxed"
                />
              </div>
            </div>

            <div className="pt-4 flex justify-end">
              <button
                onClick={() => setActiveTab("editor")}
                className="px-6 py-2.5 rounded-xl bg-violet-600 hover:bg-violet-500 text-white font-semibold text-xs transition-colors"
              >
                Proceed to Chapter Content →
              </button>
            </div>
          </div>
        )}

        {/* Tab 2: Chapter Content Editor */}
        {activeTab === "editor" && (
          <div className="glass-panel p-6 sm:p-8 rounded-3xl border border-zinc-800 space-y-6 animate-in fade-in duration-200">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div>
                <h3 className="text-lg font-bold text-white">Chapter 1 Editor</h3>
                <p className="text-xs text-zinc-400">
                  {workType === "MANGA"
                    ? "Upload high-res sequential manga/webtoon image pages."
                    : "Write or paste markdown/prose with real-time word counting."}
                </p>
              </div>

              {workType !== "MANGA" && (
                <button
                  onClick={handleRunAICritique}
                  className="px-4 py-2 rounded-xl bg-gradient-to-r from-amber-500 to-fuchsia-600 text-white text-xs font-bold flex items-center gap-1.5 shadow-md hover:scale-105 transition-all"
                >
                  <Sparkles className="w-4 h-4" /> Run AI Critique on Chapter
                </button>
              )}
            </div>

            <div className="space-y-2">
              <label className="text-xs font-bold text-zinc-300">Chapter Title</label>
              <input
                type="text"
                placeholder="e.g., Chapter 1: The Gathering of Shadows"
                value={chapterTitle}
                onChange={(e) => setChapterTitle(e.target.value)}
                className="w-full px-4 py-2.5 bg-zinc-900 border border-zinc-800 rounded-xl text-sm text-zinc-100 focus:outline-none focus:border-violet-500"
              />
            </div>

            {workType === "MANGA" ? (
              /* Manga Image Uploader */
              <div className="border-2 border-dashed border-zinc-700/80 hover:border-violet-500/80 rounded-2xl p-12 text-center bg-zinc-950/50 space-y-4 cursor-pointer transition-colors">
                <div className="w-12 h-12 rounded-2xl bg-violet-600/20 text-violet-400 flex items-center justify-center mx-auto">
                  <Upload className="w-6 h-6" />
                </div>
                <div>
                  <h4 className="text-sm font-bold text-zinc-200">Drop Manga Pages or Click to Upload</h4>
                  <p className="text-xs text-zinc-400 mt-1">Supports PNG, JPG, WebP (auto-optimized into webtoon vertical slices)</p>
                </div>
                <span className="inline-block px-4 py-1.5 rounded-full bg-zinc-800 text-xs text-zinc-300 font-semibold">
                  Browse Files
                </span>
              </div>
            ) : (
              /* Text Novel Editor */
              <div className="space-y-2">
                <div className="flex items-center justify-between text-xs text-zinc-400">
                  <span>Manuscript Text (Markdown Supported)</span>
                  <span className="font-mono text-violet-400 font-semibold">{wordCount} Words</span>
                </div>
                <textarea
                  rows={14}
                  placeholder="Paste or write your story here. Double line breaks for new paragraphs..."
                  value={chapterBody}
                  onChange={(e) => setChapterBody(e.target.value)}
                  className="w-full p-4 bg-zinc-900 border border-zinc-800 rounded-2xl text-sm text-zinc-200 font-serif leading-relaxed focus:outline-none focus:border-violet-500"
                />
              </div>
            )}

            <div className="pt-4 flex justify-between">
              <button
                onClick={() => setActiveTab("details")}
                className="px-5 py-2 rounded-xl bg-zinc-900 border border-zinc-800 text-xs font-semibold text-zinc-400 hover:text-white"
              >
                ← Back
              </button>
              <button
                onClick={() => setActiveTab("release")}
                className="px-6 py-2.5 rounded-xl bg-violet-600 hover:bg-violet-500 text-white font-semibold text-xs"
              >
                Proceed to Release Model →
              </button>
            </div>
          </div>
        )}

        {/* Tab 3: Release & Monetization Model */}
        {activeTab === "release" && (
          <div className="glass-panel p-6 sm:p-8 rounded-3xl border border-zinc-800 space-y-6 animate-in fade-in duration-200">
            <h3 className="text-lg font-bold text-white">Monetization & Access Rules</h3>
            <p className="text-xs text-zinc-400 -mt-4">
              Choose how readers access this release. You retain 100% control over your schedule.
            </p>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {/* Model 1: Free */}
              <div
                onClick={() => setMonetizationModel("FREE")}
                className={`p-5 rounded-2xl border cursor-pointer transition-all ${
                  monetizationModel === "FREE"
                    ? "bg-violet-950/30 border-violet-500 ring-2 ring-violet-500/50"
                    : "bg-zinc-900/60 border-zinc-800 hover:border-zinc-700"
                }`}
              >
                <h4 className="font-bold text-sm text-zinc-100 flex items-center justify-between">
                  100% Free Access
                  {monetizationModel === "FREE" && <CheckCircle2 className="w-4 h-4 text-violet-400" />}
                </h4>
                <p className="text-xs text-zinc-400 mt-2 leading-relaxed">
                  Available to all readers immediately. Great for building an initial audience and maximizing discovery.
                </p>
              </div>

              {/* Model 2: Members-First Early Access */}
              <div
                onClick={() => setMonetizationModel("MEMBERS_FIRST")}
                className={`p-5 rounded-2xl border cursor-pointer transition-all ${
                  monetizationModel === "MEMBERS_FIRST"
                    ? "bg-amber-950/30 border-amber-500 ring-2 ring-amber-500/50"
                    : "bg-zinc-900/60 border-zinc-800 hover:border-zinc-700"
                }`}
              >
                <div className="flex items-center justify-between">
                  <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-amber-500/20 text-amber-300 border border-amber-500/30">
                    Recommended
                  </span>
                  {monetizationModel === "MEMBERS_FIRST" && <CheckCircle2 className="w-4 h-4 text-amber-400" />}
                </div>
                <h4 className="font-bold text-sm text-zinc-100 mt-2">Members-First Early Access</h4>
                <p className="text-xs text-zinc-400 mt-1 leading-relaxed">
                  Subscribers get instant access. The chapter becomes free to the public automatically after your chosen delay.
                </p>
              </div>

              {/* Model 3: Paid Work */}
              <div
                onClick={() => setMonetizationModel("PAID")}
                className={`p-5 rounded-2xl border cursor-pointer transition-all ${
                  monetizationModel === "PAID"
                    ? "bg-emerald-950/30 border-emerald-500 ring-2 ring-emerald-500/50"
                    : "bg-zinc-900/60 border-zinc-800 hover:border-zinc-700"
                }`}
              >
                <h4 className="font-bold text-sm text-zinc-100 flex items-center justify-between">
                  Premium Paid Unlock
                  {monetizationModel === "PAID" && <CheckCircle2 className="w-4 h-4 text-emerald-400" />}
                </h4>
                <p className="text-xs text-zinc-400 mt-2 leading-relaxed">
                  Permanent paid entitlement. Readers unlock this chapter or entire volume with a direct payment.
                </p>
              </div>
            </div>

            {/* Model Configuration */}
            {monetizationModel === "MEMBERS_FIRST" && (
              <div className="p-4 rounded-2xl bg-zinc-950 border border-amber-500/30 space-y-3">
                <label className="text-xs font-bold text-amber-300 flex items-center gap-1.5">
                  <Clock className="w-4 h-4" /> Early Access Public Release Delay (Days)
                </label>
                <div className="flex items-center gap-3 max-w-xs">
                  <input
                    type="number"
                    min={1}
                    max={30}
                    value={membersFirstDays}
                    onChange={(e) => setMembersFirstDays(Number(e.target.value))}
                    className="w-24 px-3 py-2 bg-zinc-900 border border-zinc-800 rounded-xl text-sm text-white font-mono"
                  />
                  <span className="text-xs text-zinc-400">
                    Days before becoming free to all users
                  </span>
                </div>
              </div>
            )}

            {monetizationModel === "PAID" && (
              <div className="p-4 rounded-2xl bg-zinc-950 border border-emerald-500/30 space-y-3">
                <label className="text-xs font-bold text-emerald-300">Price (USD)</label>
                <div className="flex items-center gap-2 max-w-xs">
                  <span className="text-zinc-400 font-bold">$</span>
                  <input
                    type="text"
                    value={price}
                    onChange={(e) => setPrice(e.target.value)}
                    className="w-28 px-3 py-2 bg-zinc-900 border border-zinc-800 rounded-xl text-sm text-white font-mono"
                  />
                </div>
              </div>
            )}

            <div className="pt-4 flex justify-between">
              <button
                onClick={() => setActiveTab("editor")}
                className="px-5 py-2 rounded-xl bg-zinc-900 border border-zinc-800 text-xs font-semibold text-zinc-400 hover:text-white"
              >
                ← Back
              </button>
              <button
                onClick={() => setActiveTab("ai")}
                className="px-6 py-2.5 rounded-xl bg-gradient-to-r from-amber-500 to-fuchsia-600 text-white font-bold text-xs shadow-md"
              >
                Review with AI Critique Suite →
              </button>
            </div>
          </div>
        )}

        {/* Tab 4: AI Rate My Book Diagnostic */}
        {activeTab === "ai" && (
          <div className="glass-panel p-6 sm:p-8 rounded-3xl border border-zinc-800 space-y-6 animate-in fade-in duration-200">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-zinc-800">
              <div>
                <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-amber-500/20 text-amber-300 text-xs font-semibold border border-amber-500/30 mb-2">
                  <Sparkles className="w-3.5 h-3.5" /> Advisory Craft Diagnostic
                </div>
                <h3 className="text-xl font-bold text-white">AI "Rate My Book" Structural Feedback</h3>
              </div>

              <button
                onClick={handleRunAICritique}
                disabled={isAnalyzing}
                className="px-5 py-2 rounded-xl bg-violet-600 hover:bg-violet-500 disabled:opacity-50 text-white text-xs font-bold flex items-center gap-2 shadow-md transition-all"
              >
                {isAnalyzing ? "Analyzing Manuscript..." : "Re-Analyze Chapter"}
              </button>
            </div>

            {isAnalyzing ? (
              <div className="py-20 text-center space-y-4">
                <div className="w-12 h-12 border-4 border-violet-500 border-t-transparent rounded-full animate-spin mx-auto" />
                <p className="text-sm text-zinc-300 font-medium">
                  Evaluating pacing, character voice, and narrative tension...
                </p>
              </div>
            ) : aiFeedback ? (
              <div className="space-y-6">
                {/* Score Grid */}
                <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-3">
                  {Object.entries(aiFeedback.scores).map(([key, val]) => (
                    <div key={key} className="p-3.5 rounded-2xl bg-zinc-950 border border-zinc-800 text-center space-y-1">
                      <span className="text-[10px] uppercase font-bold text-zinc-400 capitalize block truncate">
                        {key.replace(/([A-Z])/g, " $1")}
                      </span>
                      <p className="text-lg font-extrabold text-violet-400">{val}</p>
                    </div>
                  ))}
                </div>

                {/* Strengths & Weaknesses */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  {/* Strengths */}
                  <div className="p-5 rounded-2xl bg-emerald-950/20 border border-emerald-800/40 space-y-3">
                    <h4 className="text-xs font-bold text-emerald-400 uppercase tracking-wider flex items-center gap-1.5">
                      <CheckCircle2 className="w-4 h-4" /> Key Strengths
                    </h4>
                    <ul className="space-y-2 text-xs text-zinc-300">
                      {aiFeedback.strengths.map((s, i) => (
                        <li key={i} className="flex items-start gap-2">
                          <span className="text-emerald-400">•</span>
                          <span>{s}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  {/* Areas for Growth */}
                  <div className="p-5 rounded-2xl bg-amber-950/20 border border-amber-800/40 space-y-3">
                    <h4 className="text-xs font-bold text-amber-400 uppercase tracking-wider flex items-center gap-1.5">
                      <AlertCircle className="w-4 h-4" /> Areas for Polish
                    </h4>
                    <ul className="space-y-2 text-xs text-zinc-300">
                      {aiFeedback.weaknesses.map((w, i) => (
                        <li key={i} className="flex items-start gap-2">
                          <span className="text-amber-400">•</span>
                          <span>{w}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>

                {/* Actionable Suggestions */}
                <div className="p-5 rounded-2xl bg-zinc-950 border border-zinc-800 space-y-3">
                  <h4 className="text-xs font-bold text-violet-400 uppercase tracking-wider">
                    Actionable Craft Suggestions
                  </h4>
                  <div className="space-y-2 text-xs text-zinc-300">
                    {aiFeedback.actionableSuggestions.map((sug, i) => (
                      <p key={i} className="p-3 rounded-xl bg-zinc-900/60 border border-zinc-800/80">
                        {i + 1}. {sug}
                      </p>
                    ))}
                  </div>
                </div>

                {/* Disclaimer */}
                <p className="text-[11px] text-zinc-500 italic text-center">
                  * {aiFeedback.disclaimer}
                </p>
              </div>
            ) : (
              <div className="py-12 text-center space-y-4">
                <Sparkles className="w-10 h-10 text-amber-400 mx-auto" />
                <h4 className="text-sm font-bold text-zinc-200">No AI Critique Run Yet</h4>
                <p className="text-xs text-zinc-400 max-w-sm mx-auto">
                  Click the button above to evaluate your drafted chapter across literary dimensions.
                </p>
              </div>
            )}
          </div>
        )}
      </main>

      <Footer />
    </div>
  );
}
